baseURL = 'https://wade.dev/'
languageCode = 'en-us'
title = 'Nicholas Wade Website'
theme = "poison"
paginate=10
pluralizelisttitles = false

[params]
  brand="Nicholas Wade"
  description="My Personal Website"
  dark_mode=true
  front_page_content = ["about"]
  menu = [
    {Name = "About Me", URL = "/about/", HasChildren = true, Limit=2},
    {Name = "Projects", URL = "/projects/", HasChildren = true, Limit=3},
    {Name = "Lists", URL = "", HasChildren = true, Limit = 2},
    #{Name = "Reading List", URL = "https://nkwade.notion.site/Reading-List-0bb176adccd34b1c880de7e2516b8014/", External = true},
    {Name = "Medium Page", URL = "https://medium.wade.dev", External = true},
  ]

  # Links to your socials.  Comment or delete any you don't need/use. 
    #discord_url = "https://discord.com"
    email_url = "mailto://nicholas@wade.dev"
    github_url = "https://github.com/nkwade"
    linkedin_url = "https://linkedin.com/in/nkwade/"
    #twitter_url = "https://twitter.com/nkwade"
    youtube_url = "https://youtube.com/@nkwade"
    medium_url = "medium.wade.dev"